// frontend/src/modules/Properties/constants/features.ts

export const PROPERTY_FEATURES = {
  // Особенности объекта
  property: [
    'mediaRoom',
    'privateGym',
    'privateLift',
    'privateSauna',
    'jacuzzi',
    'cornerUnit',
    'maidsQuarters',
    'duplex',
    'balcony',
    'westernKitchen',
    'bathtub',
    'smartHome',
    'privatePool',
    'sharedPool',
    'securitySystem',
    'airConditioning',
    'heating',
    'fireplace',
    'solarPanels',
    'waterHeater',
    'washer',
    'dryer',
    'dishwasher',
    'microwave',
    'oven',
    'refrigerator',
    'freeParking',
    'paidParking',
    'evCharger',
    'elevator',
    'wheelchairAccessible',
    'smokeDetector',
    'carbonMonoxideDetector',
    'firstAidKit',
    'fireExtinguisher',
    'lockOnBedroomDoor',
    'hangers',
    'bedLinens',
    'extraPillowsBlankets',
    'roomDarkeningShades',
    'ironIroningBoard',
    'mosquitoNet',
    'cribAvailable',
    'highChair',
    'boardGames',
    'freeWeights',
    'exerciseEquipment',
    'yoga'
  ],

  // Внешние особенности
  outdoor: [
    'garden',
    'terrace',
    'rooftop',
    'bbqArea',
    'outdoorShower',
    'garage',
    'coveredParking',
    'carport',
    'poolBar',
    'summerKitchen',
    'outdoorDining',
    'playground',
    'petArea',
    'storageRoom',
    'laundryRoom',
    'outdoorFurniture',
    'sunLoungers',
    'hammock',
    'gazebo',
    'pondOrStream',
    'outdoorKitchen',
    'firepit',
    'hotTub',
    'beachEssentials',
    'privateBeachAccess',
    'lakefront',
    'skiInSkiOut'
  ],

  // Условия аренды
  rental: [
    'maidService',
    'chefService',
    'airportTransfer',
    'carRental',
    'breakfastIncluded',
    'cleaning',
    'linenChange',
    'utilitiesIncluded',
    'wifiIncluded',
    'cableTv',
    'conciergeService',
    'securityGuard',
    'management',
    'longTermStaysAllowed',
    'petsAllowed',
    'eventsAllowed',
    'smokingAllowed',
    'photographyAllowed',
    'suitableForInfants',
    'suitableForChildren',
    'suitableForPets'
  ],

  // Расположение
  location: [
    'beachAccess',
    'beachFront',
    'nearSchool',
    'nearHospital',
    'nearSupermarket',
    'nearRestaurant',
    'nearGolfCourse',
    'nearMarina',
    'nearAirport',
    'nearBusStop',
    'quietArea',
    'gatedCommunity',
    'cityCentre',
    'nearPublicTransport',
    'nearHighway',
    'nearMall',
    'nearPark',
    'nearGym',
    'nearSpa',
    'nearDivingSite',
    'nearSurfSpot',
    'walkingDistance',
    'bikeDistance',
    'waterfront',
    'mountainside',
    'countryside',
    'urban',
    'suburban',
    'rural',
    'historic',
    'resort'
  ],

  // Виды
  views: [
    'seaView',
    'mountainView',
    'poolView',
    'gardenView',
    'cityView',
    'panoramicView',
    'partialSeaView',
    'lakeView',
    'forestView',
    'riverView',
    'valleyView',
    'sunsetView',
    'jungleView',
    'riceFieldView',
    'islandView',
    'beachView',
    'skylineView',
    'courtyardView',
    'streetView'
  ]
};

export const RENOVATION_TYPES = {
  full: 'full',
  partial: 'partial'
};