// backend/src/constants/features.ts
export const PROPERTY_FEATURES = {
  property: [
    'mediaRoom', 'privateGym', 'privateLift', 'privateSauna', 'jacuzzi', 'cornerUnit',
    'maidsQuarters', 'duplex', 'triplex', 'balcony', 'study', 'library', 'winecellar',
    'elevator', 'homeElevator', 'gameRoom', 'billiardRoom', 'kidsRoom', 'nursery',
    'guestRoom', 'serviceRoom', 'utilityRoom', 'pantry', 'wetRoom', 'powderRoom',
    'ensuiteBathroom', 'sharedBathroom', 'outdoorBathroom', 'steamRoom', 'hammam',
    'massage', 'yogaRoom', 'meditationRoom', 'artStudio', 'workshop', 'westernKitchen',
    'thaiKitchen', 'openKitchen', 'closedKitchen', 'bathtub', 'shower', 'separateShower',
    'privatePool', 'sharedPool', 'infinityPool', 'kidPool', 'smartHome', 'securitySystem',
    'cctv', 'alarmSystem', 'intercom', 'videoIntercom', 'safebox', 'airConditioning',
    'centralAC', 'heating', 'floorHeating', 'fireplace', 'solarPanels', 'waterHeater',
    'solarWaterHeater', 'generator', 'ups', 'highCeiling', 'largeWindows',
    'floorToFloorWindows', 'walkinCloset', 'builtinWardrobe', 'separateEntrance',
    'privateEntrance', 'soundproofing', 'waterFiltration', 'airPurifier', 'washer',
    'dryer', 'dishwasher', 'refrigerator', 'microwave', 'oven', 'stove', 'gasStove',
    'electricStove', 'inductionStove', 'coffeemaker', 'waterDispenser', 'tv', 'smartTV',
    'wifi', 'highSpeedInternet', 'fiberOptic', 'telephone', 'satelliteTV', 'surround',
    'homeTheater', 'musicSystem', 'piano', 'furnished', 'partiallyFurnished',
    'fullyEquipped', 'euroRenovation', 'designerRenovation', 'modernDesign',
    'traditionalStyle', 'minimalist', 'luxury', 'penthouseLevel', 'groundFloor',
    'topFloor', 'multiLevel', 'studio', 'openPlan', 'petFriendly', 'childFriendly',
    'wheelchair', 'disabledAccess', 'ramp', 'emergencyExit', 'fireExtinguisher',
    'firstAidKit', 'smokeDetector', 'carbonMonoxide', 'eco', 'energyEfficient',
    'sustainable', 'greenBuilding', 'leed', 'newConstruction', 'underConstruction',
    'readyToMove', 'offPlan', 'resale'
  ],
  outdoor: [
    'garden', 'privateGarden', 'landscaped', 'tropicalGarden', 'japaneseGarden',
    'vegetableGarden', 'fruitTrees', 'flowerGarden', 'terrace', 'rooftop',
    'rooftopTerrace', 'skyGarden', 'bbqArea', 'outdoorKitchen', 'outdoorShower',
    'beachShower', 'summerKitchen', 'outdoorDining', 'lounge', 'sunbeds', 'sunshade',
    'pergola', 'gazebo', 'pavilion', 'garage', 'carport', 'coveredParking',
    'openParking', 'secureParking', 'guestParking', 'electricCarCharger',
    'bikestorage', 'poolBar', 'fountain', 'pond', 'koiPond', 'waterfall', 'streambed',
    'playground', 'swingSet', 'slide', 'sandbox', 'trampoline', 'petArea', 'dogRun',
    'petShower', 'storageRoom', 'shed', 'greenhouse', 'laundryRoom', 'dryingArea',
    'outdoorGym', 'sportsArea', 'tennisCourt', 'basketballCourt', 'footballField',
    'volleyball', 'badminton', 'puttingGreen', 'bocce', 'skatepark', 'joggingTrack',
    'walkingPath', 'cyclingPath', 'fishingPier', 'boatDock', 'marina', 'beachAccess',
    'privateBeach', 'beachCabana', 'fence', 'wall', 'gate', 'electricGate',
    'securityGate', 'driveway', 'pavedDriveway', 'gravelDriveway', 'streetLighting',
    'gardenLighting', 'securityLighting', 'decorativeLighting', 'sprinklerSystem',
    'automaticSprinklers', 'drip', 'irrigationSystem', 'rainwaterCollection', 'well',
    'borehole', 'waterTank', 'waterPump', 'septicTank', 'sewageSystem', 'drainageSystem'
  ],
  rental: [
    'maidService', 'dailyCleaning', 'weeklyCleaning', 'chefService', 'privateChef',
    'cateringService', 'driverService', 'airportTransfer', 'carRental', 'bicycleRental',
    'scooterRental', 'boatRental', 'kayakRental', 'breakfastIncluded', 'halfBoard',
    'fullBoard', 'allInclusive', 'cleaning', 'linenChange', 'towelChange',
    'laundryService', 'dryClean', 'ironing', 'utilitiesIncluded', 'electricityIncluded',
    'waterIncluded', 'gasIncluded', 'wifiIncluded', 'internetIncluded', 'cableTv',
    'streamingServices', 'conciergeService', '24hConcierge', 'securityGuard',
    '24hSecurity', 'management', 'propertyManagement', 'maintenance', 'repairService',
    'gardenMaintenance', 'poolMaintenance', 'pestControl', 'wasteDisposal', 'recycling',
    'petCare', 'petSitting', 'dogWalking', 'babysitting', 'childcare', 'eldercare',
    'medicalService', 'nurseOnCall', 'doctorOnCall', 'ambulance', 'pharmacy', 'grocery',
    'shopping', 'delivery', 'courierService', 'mailHandling', 'packageReceiving',
    'valetParking', 'carWash', 'carService', 'snorkeling', 'divingEquipment', 'fishing',
    'surfingLessons', 'kitesurfing', 'wakeboarding', 'jetski', 'parasailing',
    'bananaBoat', 'speedboat', 'yachtCharter', 'helicopterService', 'privatePlane',
    'limousineService', 'tourBooking', 'ticketBooking', 'restaurantReservation',
    'spaBooking', 'massageService', 'beautyService', 'hairSalon', 'nailSalon',
    'personalTrainer', 'yogaInstructor', 'pilatesInstructor', 'tennisCoach', 'golfCoach',
    'swimInstructor', 'eventPlanning', 'partyPlanning', 'weddingPlanning', 'catering',
    'florist', 'photographer', 'videographer', 'musician', 'dj', 'entertainer',
    'translation', 'interpreter', 'legalService', 'lawyer', 'notary', 'accounting',
    'taxService', 'insurance', 'visaAssistance', 'immigration', 'relocation', 'storage',
    'furnitureRental', 'applianceRental', 'shortTermRental', 'longTermRental',
    'monthlyRental', 'weeklyRental', 'dailyRental', 'flexibleCheckIn', 'lateCheckOut',
    'earlyCheckIn', 'depositRequired', 'noDeposit', 'creditCardRequired', 'cashPayment',
    'bankTransfer', 'onlinePayment', 'installmentPlan', 'discountAvailable',
    'seasonalDiscount', 'longStayDiscount', 'earlyBooking', 'lastMinute',
    'studentDiscount', 'seniorDiscount', 'militaryDiscount', 'corporateRate', 'groupRate',
    'noSmoking', 'smokingAllowed', 'noPets', 'noParties', 'quietHours', 'noiseCurfew',
    'minimumAge', 'adultsOnly', 'familyFriendly', 'kidfriendly', 'infantFriendly',
    'teenagerFriendly'
  ],
  location: [
    'beachAccess', 'beachFront', 'secondLine', 'walkToBeach', 'nearSchool',
    'nearInternationalSchool', 'nearKindergarten', 'nearUniversity', 'nearHospital',
    'nearClinic', 'nearPharmacy', 'nearSupermarket', 'nearConvenience', 'nearMarket',
    'nearMall', 'nearShops', 'nearRestaurant', 'nearCafe', 'nearBar', 'nearNightlife',
    'nearGolfCourse', 'nearMarina', 'nearYachtClub', 'nearTennisCourt', 'nearBasketball',
    'nearFootball', 'nearVolleyball', 'nearSkatepark', 'nearGym', 'nearFitness',
    'nearYoga', 'nearSpa', 'nearWellness', 'nearAirport', 'nearBusStop',
    'nearBusTerminal', 'nearTaxiStand', 'nearMetro', 'nearTrain', 'nearHighway',
    'nearMainRoad', 'nearBank', 'nearAtm', 'nearPostOffice', 'nearPolice',
    'nearFireStation', 'nearEmbassy', 'nearGovernment', 'nearSalon', 'nearVet',
    'nearPetShop', 'nearTemple', 'nearMosque', 'nearChurch', 'nearSynagogue', 'nearPark',
    'nearPlayground', 'nearGarden', 'nearForest', 'nearMountain', 'nearLake', 'nearRiver',
    'nearWaterfall', 'nearNationalPark', 'nearNatureReserve', 'nearZoo', 'nearAquarium',
    'nearMuseum', 'nearGallery', 'nearTheater', 'nearCinema', 'nearConcertHall',
    'nearStadium', 'nearSportsCenter', 'nearLibrary', 'nearBookstore',
    'nearTouristAttraction', 'nearLandmark', 'nearViewpoint', 'nearDiveSite',
    'nearSurfSpot', 'nearSnorkeling', 'nearHiking', 'nearCycling', 'nearJogging',
    'quietArea', 'peacefulLocation', 'residentialArea', 'commercialArea',
    'businessDistrict', 'touristArea', 'localArea', 'expatArea', 'internationalCommunity',
    'gatedCommunity', 'secureComplex', 'privateCommunity', 'luxuryDevelopment',
    'newDevelopment', 'establishedArea', 'upAndComing', 'trendyArea', 'historicDistrict',
    'culturalQuarter', 'artDistrict', 'entertainmentDistrict', 'financialDistrict',
    'shoppingDistrict', 'cityCentre', 'cityCenter', 'downtown', 'midtown', 'uptown',
    'suburb', 'outskirts', 'countryside', 'rural', 'urban', 'metropolitan', 'coastal',
    'inland', 'hillside', 'hilltop', 'valley', 'plateau', 'peninsula', 'island',
    'mainland', 'waterfront', 'riverside', 'lakeside', 'mountainside', 'forestEdge',
    'parkside', 'greenBelt', 'openSpace', 'lowDensity', 'highDensity', 'mixedUse',
    'liveworkPlay', 'masterPlanned', 'smartCity', 'ecoVillage', 'sustainableCommunity',
    'walkable', 'bikeFriendly', 'publicTransport', 'transitOriented', 'carDependent',
    'carFree', 'pedestrianZone', 'lowTraffic', 'noThroughTraffic', 'deadEnd', 'culDeSac',
    'mainStreet', 'sideStreet', 'privateStreet', 'pavedRoad', 'dirtRoad',
    'streetParking', 'wellLit', 'darkAtNight', 'safeArea', 'lowCrime', 'neighborhood',
    'communitySpirit', 'familyOriented', 'professionalArea', 'studentArea',
    'retirementCommunity'
  ],
  views: [
    'seaView', 'oceanView', 'beachView', 'bayView', 'coastalView', 'partialSeaView',
    'glimpseOfSea', 'distantSeaView', 'sunsetView', 'sunriseView', 'mountainView',
    'hillView', 'volcanoView', 'forestView', 'lakeView', 'riverView', 'waterfallView',
    'pondView', 'poolView', 'gardenView', 'parkView', 'cityView', 'skylineView',
    'panoramicView', 'unobstructedView', '180View', '360View', 'scenicView',
    'spectacularView', 'breathtakingView', 'stunningView', 'magnificentView',
    'beautifulView', 'niceView', 'pleasantView', 'rooftopView', 'balconyView',
    'terraceView', 'windowView', 'floorToFloorView', 'elevatedView', 'groundLevelView',
    'skylightView', 'noView', 'obstructedView', 'limitedView', 'interiorView',
    'courtyardView', 'atriumView', 'streetView', 'roadView', 'parkingView', 'neighborView',
    'wallView', 'buildingView', 'roofView', 'towerView', 'bridgeView', 'monumentView',
    'templeView', 'palaceView', 'castleView', 'stadiumView', 'airportView', 'portView',
    'marinaView', 'yachtView', 'boatView', 'shipView', 'islandView', 'horizonView',
    'clearView', 'privateView', 'sharedView', 'facingNorth', 'facingSouth', 'facingEast',
    'facingWest', 'northeastView', 'northwestView', 'southeastView', 'southwestView'
  ]
};